README.rst
This change adds the step of removing Unicode characters from the URL and replacing them with their punycode escape sequences.
=> Adding Punycode decoding step

README.rst
I'm pretty sure it's the third.
=> Passes the third parameter

README.rst
Just an overview - can be expanded
=> Interrupts overview and kernel entry

README.rst
More descriptions on JS execution and HTML resource parsing
=> HTML Parsing and resource fetching

README.rst
I've added a section describing the basics of HTTP. There's obviously a lot of things missing and ways that this can be improved (ie. it can go into more details about protocol negotiation, upgrading to HTTPS or SPDY, different possibilities for response codes, etc), but this is a start.
=> Added first draft of section on HTTP protocol.

README.rst
Added a reference to the OS looking into its /etc/hosts file before trying to look up a hostname through DNS.
=> Added checking of hosts file before trying DNS

README.rst
I caught some typos in my pull request right after it was merged, and now it's too late to rewrite them out of history ("speedy"? What was I thinking!)
=> Fixed some embarrassing typos

README.rst
Explain that there is queue of messages for the window.
=> Expand the WindowProc information

README.rst
Added HTTPD Explanation.
Hope I'm doing it right this time :-)
=> Added HTTPD Explanation

README.rst
- Corrected and extra details for USB keyboard
- GNU/Linux GUI keystrokes handling process
- TLS handshake process
* Misspellings corrected from previus failed pull request
=> USB extra details, GNU/Linux keystrokes process, TLS brief handshake process added

README.rst
See:
http://docutils.sourceforge.net/docs/ref/rst/directives.html#table-of-contents
=> Added table of contents

README.rst
- CSS parsing detail added
- GPU rendering process (no hardware internals yet)
- URL parsing (URL parts)
- Virtual Keyboard case added
=> CSS parsing, GPU rendering, URL parsing

README.rst
There's actually room for some more improvements, but these are the ones that ought not to cause any form of discussion.
=> Various improvements: typos, spelling and grammar

README.rst
=> Mentioned evdev as this is used by X to read keypresses

README.rst
Sometimes incoming requests are rewritten via a rewrite module.  I added
some information about URL rewrites.
=> Added information about rewrite rules.

README.rst
Link to Wikipedia for an extensive list of hosts file locations, including mobile OS.
=> The location of the hosts file varies by OS.

README.rst
Added a short explanation of how the HSTS list works and why it's important.
Awesome idea, thanks for making this repo :)
=> HSTS explanation

README.rst
I added information on the url sent to the search engine.
=> Added Detail to "Is it a URL or a search term?" Section

README.rst
Updating a few information about HTML parsing, Will write more in detail. 
+1 for creating the repo.
=> HTML parsing information updated

README.rst
Fixed issues mentioned in pull request #145.
=> Fixed issues mentioned in pull request #145

README.rst
Fixed the build errors in pull request #136
=> Fixed build errors

README.rst
Fixed Build Errors in Pull Request #152
=> Fixed Build Errors in Pull Request #152

README.rst
Expanded, fixed issues with, and merged pull requests #161 and #162.
=> Merged multiple pull requests

README.rst
Hi! I think that the OSI Model is really important to mention! :)
=> Clarify 'ARP' and 'Layer 2'

README.rst
filled up full HTTP request methods.
ref: 
https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9 (before 2014)
https://tools.ietf.org/html/rfc7231#section-4.3 (nowadays)
=> filled up full HTTP request methods

README.rst
I created Korean translation of this.
I followed the way Chinese translation's author did on his work.
So, I made my own repo and added link here!
=> add link to Korean translation

README.rst
- FIX grammatical errors
- REDUCE wordy sentences
- REMOVE extraneous statement: "But, a whole lot happens... which isn't explained" (should not be stated in docs, but as an issue)
- REMOVE extraneous adjectives
=> docs: the "g" key is pressed

README.rst
Hi, I translated the excellent work into Japanese.
I followed the way previous translators added their links.
Hope you merge it!
Thanks
=> add link to Japanese translation

README.rst
I didn't go into too much details on the differences between algorithms or when congestion control performs badly (high throughput, high packet loss), but I can if you like :)
=> Add a section on TCP congestion control
